### ISSUE TITLE
EnumMap

### ISSUE THREAD

**Issue by hhhansen** [Lawo/ember-plus#97]
It seems that 'EnumMap' isn't working in the latest versions of the EmberViewer and/or EmberSlim. 'Enumeration' is working well.

**Comment by mkeuck** [comment]
Hi,
the libember slim does not support the enum-map at all, but only the standard enumeration transmitted as single string separated with the '`\n'` character.
This decision was made because the C version was written for hardware with very limited resources. If it helps, fields can be hidden by adding a `~` character at the beginning of an enumeration entry. That way, non-linear indices can be generated: `"0\n~1\n2"`
